#!/bin/bash
aws ec2 run-instances \
    --image-id ami-0f5ee92e2d63afc18 \
    --instance-type t2.micro \
    --key-name powershell \
    --security-group-ids sg-058faade30c71445d \
    --count 1 \
    --region ap-south-1 \
    --tag-specifications jacli